---
language: node_js
node_js:
  - "0.12"

sudo: required
dist: trusty

cache:
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: a0abb57473b09b2720bafaf462b967f49c365444a854f5deece7c62df7048319



env:
  - EMBER_TRY_SCENARIO=default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary


before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g codeclimate-test-reporter"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test

after_script:
  - codeclimate-test-reporter < lcov.dat

